// build.js - fetches OpenAPI spec and writes data.js
const fs = require('fs');
const https = require('https');

const SPEC_URL = 'https://api.fluxer.app/openapi.json';
const OUTPUT_FILE = 'data.js';

console.log(`Fetching OpenAPI spec from ${SPEC_URL}...`);

https.get(SPEC_URL, (res) => {
    let rawData = '';
    res.on('data', (chunk) => { rawData += chunk; });
    res.on('end', () => {
        try {
            const json = JSON.parse(rawData);
            const content = `// Auto-generated by build.js\nconst FLUXER_SPEC = ${JSON.stringify(json, null, 2)};\n`;
            fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
            console.log(`✅ Successfully wrote ${OUTPUT_FILE}`);
        } catch (err) {
            console.error('❌ Failed to parse or write:', err.message);
            process.exit(1);
        }
    });
}).on('error', (err) => {
    console.error('❌ Network error:', err.message);
    process.exit(1);
});